### ISSUE TITLE
Engine must run users' code securely

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-engine#11]
In the interest of security, I'd like to try using FreeBSD jails when running users' code, for several reasons:
- they provide a simple solution to the enormous security risk of running user-provided code
- they provide a significantly lighter solution than using a full virtual machine
- they provide operating system-level virtualization
- they are indistinguishable from a real system, providing users an unadulterated environment for their programs
- they disallow users from disrupting each other's programs
- they allow us to easily and safely grant access to a full, virtualized system (filesystem, shell, etc.)
 
**Update**: *I decided to use Linux Containers (LXC) before FreeBSD jails. By following the modular design specified below, we can add support for jails in the future.*

Ideally, this should be implemented in a modular fashion. In other words:
- use of jails/LXC should not be hard-coded into each runner - it should be abstracted out
- it should be easy to discontinue or re-continue using jails/LXC in the Engine (easy as disabling and re-enabling a browser plugin)
- this probably means this feature this be implemented as a module shared by all runners
 
For this issue to be deemed resolved, the following tasks must be completed:
- [ ] experiment with using jails/LXC in the command line
- [ ] research jail/LXC configuration for restricting user programs' ability from reaching the host system
- [ ] design the interface for the module that will allow the Engine to use jails/LXC
- [ ] implement the module

**Comment by ali-ramadhan** [comment]
I think you've basically implemented everything here so I'll let you close it.
