### ISSUE TITLE
Engine must run users’ programs in parallel

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-engine#12]
At the moment, running the Engine WSGI on Gunicorn might not be running users' programs in parallel. First, test the Engine to find out whether it is already set up to run multiple programs in parallel.

Refer to https://stackoverflow.com/questions/40374607/multithreading-falcon-in-python regarding spawning multiple workers with Gunicorn.

**Comment by ali-ramadhan** [comment]
We can specify number of gunicorn workers in the [Makefile](https://github.com/project-lovelace/lovelace-engine/blob/master/Makefile) which should take care of this. I don't know much about how gunicorn and falcon work but if I assume we don't have to worry about the case when a submission is made while all workers are busy.

**Comment by basimr** [comment]
When we added more workers, the engine failed. There's work to be done to make parallel code checking work.

**Comment by ali-ramadhan** [comment]
Gunicorn seems to be fine with `--workers 2` which is now the default in the `Dockerfile` and tests pass in PR #67 so I'll close this issue.
