### ISSUE TITLE
Add support for Fortran

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-engine#14]
Depends on #13 

Fortran user programs must be compiled first, so that functionality must be implemented for this issue.

**Comment by ali-ramadhan** [comment]
Out of curiosity, why Fortran?

**Comment by basimr** [comment]
Why not Fortran?

More seriously, I'd like to add a runner for a compiled language and I wanted to try using Fortran. Perhaps the novelty will mean users will also try something new. After implementing the Fortran runner, it should be easy to add runner for other (more popular) compiled languages like C and Java.

**Comment by ali-ramadhan** [comment]
I think very few people use Fortran that it's not worth considering as one of the first other languages. C and Java should come way before Fortran for us.
