### ISSUE TITLE
Fix issue where python processes run forever

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-engine#23]
In production, we often saw processes named like “python3 /root/XXXXX.run.py” inside the container run for more long periods of time without being killed. We should investigate why they're running so long, and why they aren't being killed.

**Comment by ali-ramadhan** [comment]
I think this may be related to leftover files from instances when issue #19 crops up (engine stalls and file is not deleted).

**Comment by ali-ramadhan** [comment]
Our infrastructure is pretty different now with Docker containers and I haven't seen this issue in a while so I assume it just fixed itself.
