### ISSUE TITLE
Switch from running code in LXC to Docker?

### ISSUE THREAD

**Issue by ali-ramadhan** [project-lovelace/lovelace-engine#59]
Building LXC images is a pain (from #58) and it seems like we want to use Docker anyways...

From searching around it seems security-wise LXC and Docker are pretty similar.

Probably won't happen soon as it's not high priority but might be a future improvement.

@basimr do you remember why you stuck with LXC over Docker?

**Comment by benallan** [comment]
So I've set up a quick test where I've replaced most of the lxd calls in the code_runner with docker. There's a bit more to do, but this much is working: 

- The engine connects to docker when it starts up
- Creates a code runner container
- Copies the necessary files into it
- Tears down the container when the engine exists. 

I still need to finish the code runner, then check it works properly. I also modified the engine API tests a bit so we can use them on different systems. 

I have a couple of questions about the architecture though: I had thought that the engine flow was like this:

1. Engine starts up.
2. User 1 sends submission.
3. Container 1 is created. 
4. Container 1 is deleted.
5. User 2 sends submission. 
6. Container 2 is created. 
7. ... etc

i.e. With one container per user submission. But now that I look at the lxd code, it seems like this is what's happening:

1. Engine starts. 
2. Container is created. 
3. User 1 sends submission.
4. User 2 sends submission.
5. ...etc.

Am I right that all the submissions are executed in the same container? I'm not very familiar with lxc, so I could easily be wrong!

For now I've followed the same approach as the previous lxc one when using docker, but it might be better to use one container per submission (hopefully it's not too slow). Once the code is tidied up a bit we should be able to keep both the docker and lxc as backend options too.

**Comment by benallan** [comment]
Work-in-progress code is here: https://github.com/benallan/lovelace-engine/tree/docker-test

As soon as the code runner is working by itself I'll open a PR to this repo. Merge into the docker branch?

**Comment by benallan** [comment]
I think it's quite usable now, if you'd like to give it a try @ali-ramadhan.
https://github.com/benallan/lovelace-engine/tree/6b126a593d5f8aeaf4378f0a9fd3ef02b142202a

Now that it's basically working we could think about refactoring it, depending on what you think about the questions above.

**Comment by ali-ramadhan** [comment]
> So I've set up a quick test where I've replaced most of the lxd calls in the code_runner with docker.

That's super awesome, thanks for taking this on! Sounds like most of the work is done.

> Am I right that all the submissions are executed in the same container? I'm not very familiar with lxc, so I could easily be wrong!

Yes! Yeah I guess it's a little different from Docker but LXC containers take a while to spin up so we decided to keep the container running all the time so user submissions are processed in a few seconds as opposed to 20+ seconds (forgot exactly how long it takes LXC containers to spin up).

> but it might be better to use one container per submission

Yeah my understanding is that Docker containers spin up quickly so we could probably do this. Although with your new `pytest` framework (PR #63) that outputs the time it took to run all the tests, should be easy to benchmark persistent Docker container vs. one container per submission.

> I think it's quite usable now, if you'd like to give it a try

Awesome, you work fast haha! Sounds like it's worth opening a new PR with it?

I'll give it a try tomorrow morning. I assume I have to build the `code_runner` image first?

Maybe we can talk about it if we end up chatting or screensharing.

**Comment by benallan** [comment]
Well, although I said it's "usable", I think there are still a few things to sort out! The main one is the speed: it's taking much longer to run through each solution submission so on my mac it takes a couple of minutes to run though all the tests. I think I know why: the docker copy operation is quite slow, and it's currently copying the files one by one into the container.

I thought it might be helpful to follow the same approach as you used with lxd at first, then once everyone is familiar with docker we can re-structure it to speed it up a bit. Specifically, we could mount a folder as a volume which can share files inside the container, then there's no need for any `docker cp` operations at all. This is also the first time I've used the docker python api, so there are probably a lot of optimizations to be made.

Docker containers should spin up quite fast, but even if it took a little bit of extra time for each submission it's probably still better security to use a separate container for each run. I can take a look at this later. 

Oh and there's no need to build any images explicitly, luckily! As long as you have docker installed (and running), the function `docker_init` will build the image based on the dockerfile. So the first time you run it you might notice logs related to building the image, and it might take 30-60 seconds or something, but after that the image will be cached locally and won't need to be re-built each time. It's also possible to build the image explicitly with the `docker build` command. Hopefully if you just run the engine the same as before, it'll run ok (but let me know if/when the inevitable errors appear!).

I've opened a PR: https://github.com/project-lovelace/lovelace-engine/pull/64

**Comment by ali-ramadhan** [comment]
We forgot to close this issue when PR #64 was merged. Thanks again @benallan!

Website is being dockerized as well with `docker-compose` and the lovelace-engine as a subcomponent: https://github.com/project-lovelace/lovelace-website/pull/69
