### ISSUE TITLE
Setup a custom global logger.

### ISSUE THREAD

**Issue by ali-ramadhan** [project-lovelace/lovelace-engine#8]
We should decide on a logger configuration to use for lovelace-engine and lovelace-problems. Also do we call it log or logger? Maybe we should store the logger config in an ini-style file then every file just loads it up.

**Comment by basimr** [comment]
This page looks good for inspiration and info on logging best practices in Python: https://python-guide-pt-br.readthedocs.io/en/latest/writing/logging/

**Comment by ali-ramadhan** [comment]
Awesome, thanks. I'll try configuring a logger using that.

**Comment by ali-ramadhan** [comment]
Meant 'closes', not 'clases' in my commit.
